### ISSUE TITLE
Hello, thank you for the excellent reinplemantation of LoFTR. In the "WIP" term, I see the metrics you implement is coming. How is it going?

### ISSUE THREAD

**Issue by zzxyzz** [HJoonKwon/loftr-pytorch#5]
I am waiting for that. Will that include "Mean Matching Accuracy(MMA)"?

**Comment by HJoonKwon** [comment]
Sorry. Due to some personal issues, I cannot spend much time these days on this repo. But the evaluation part would be easy to find out (see SuperPoint or LoFTR original repo). The hardest part, which is I think the training and data processing, has already been implemented in this repo.
